### ISSUE TITLE
web page publication does not work anymore

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/nasa-pds.github.io#14]
See new workflow which shows now in the github actions:
https://github.com/NASA-PDS/nasa-pds.github.io/runs/4565750823?check_suite_focus=true

This sounds like it is releated to a github updated, I posted a ticket to the github support 
https://support.github.com/ticket/personal/0/1433621

**Comment by jordanpadams** [comment]
this has been fixed but we need to follow up on erroneous email notifications
